apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-domain-writer
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-domain-writer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-domain-writer
subjects:
  - kind: ServiceAccount
    name: node-domain-sa
    namespace: default
